'use strict';

/**
 * Main App Controller
 * Controller of the ngCarAppApp
 */
angular.module('ngCarAppApp')
  .controller('MainCtrl', function ($scope, $http, db, inventory, $modal) {

    $scope.cars = [];   //Initialize empty cars array

    inventory.grab().then(function (result) { //Load data from DB
      $scope.cars = result; //Populate array with objects from DB
    });

    $scope.edit = function (car, index) {
      var editInstance = $modal.open({  //Initialize edit modal instance
        templateUrl: '../../views/edit.html',
        controller: 'EditCtrl',
        size: 'lg',
        resolve: {
          carEdit: function () {  //Pass selected car to EditCtrl modal controller
            return car;
          }
        }
      });
      editInstance.result.then(function (carEdit) {
        save(carEdit, index); //Save car to database and add to DOM
      });
    }

    $scope.remove = function (item, index) {
      inventory.remove(item); //Delete object in DB
      domRemove(index); //Update DOM to show deletion
    }

    function save(car, index) {
      inventory.upload(car.value).then(function (response) {  //POST request
        car.value._rev = response.data.rev; //Get revision hash generated by server
        if (index === undefined) {  //If the car is new
          car.value._id = response.data.id; //Get server generated hash ID
          car.id = response.data.id;
          domCreate(car);
        } else domUpdate(car, index); //Update DOM
      });
    }

    function domUpdate(item, index) {
      $scope.cars[index] = item;  //Update existing item index bound to DOM
    }

    function domRemove(index) {
      $scope.cars.splice(index, 1); //Delete existing index from DOM
    }

    function domCreate(item) {
      $scope.cars.push(item); //Push new item into DOM
    }

  });

